/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#544fc0',
        onSecondaryFixed: '#3f3f43',
        onSecondaryContainer: '#515155',
        tertiaryFixedDim: '#d0c7e8',
        onSurfaceVariant: '#485f8d',
        onPrimaryFixed: '#332c9f',
        surfaceContainer: '#e9edff',
        onPrimaryContainer: '#4741b3',
        surfaceContainerHigh: '#e1e8ff',
        tertiaryContainer: '#dfd5f7',
        background: '#f9f9ff',
        surfaceDim: '#ccdaff',
        inversePrimary: '#8c88fd',
        tertiaryFixed: '#dfd5f7',
        onBackground: '#19315d',
        primaryFixed: '#e2dfff',
        surfaceContainerHighest: '#d8e2ff',
        primaryFixedDim: '#d3d0ff',
        secondaryFixed: '#e4e2e6',
        errorContainer: '#fe8983',
        surfaceTint: '#544fc0',
        surface: '#f9f9ff',
        inverseSurface: '#070e1d',
        surfaceVariant: '#d8e2ff',
        tertiary: '#625b77',
        onSecondary: '#faf8fc',
        surfaceContainerLowest: '#ffffff',
        onTertiaryFixedVariant: '#59526e',
        primaryContainer: '#e2dfff',
        onTertiaryFixed: '#3c3650',
        onSecondaryFixedVariant: '#5b5b5f',
        onPrimaryFixedVariant: '#514cbd',
        inverseOnSurface: '#969db0',
        surfaceBright: '#f9f9ff',
        error: '#9f403d',
        onError: '#fff7f6',
        secondaryContainer: '#e4e2e6',
        onTertiary: '#fdf7ff',
        onTertiaryContainer: '#4f4964',
        outline: '#647aab',
        errorDim: '#4e0309',
        secondaryDim: '#535356',
        secondaryFixedDim: '#d5d3d8',
        secondary: '#5f5f62',
        onSurface: '#19315d',
        tertiaryDim: '#564f6b',
        surfaceContainerLow: '#f1f3ff',
        onPrimary: '#faf6ff',
        outlineVariant: '#9bb2e5',
        primaryDim: '#4742b3',
        onErrorContainer: '#752121',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        editorial: '0 12px 40px rgba(25, 49, 93, 0.06)',
      },
      borderRadius: {
        editorial: '1rem',
      },
    },
  },
  plugins: [],
}
